version: '3.7'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql-container
        ports:
            - "3306:3306"
        # build: ./api/db
        environment: 
            MYSQL_DATABASE: fakebuscape
            MYSQL_ROOT_PASSWORD: davidfico
        volumes:
            - ./src/migration/dbdocker:/var/lib/mysql
        restart: always