version: '3.7'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql-container
        environment: 
            MYSQL_DATABASE: fakebuscape
            MYSQL_ROOT_PASSWORD: davidfico
            
        volumes:
            - ./src/migration/dbdocker:/var/lib/mysql
        restart: always

    # api:
    #     build: ./
    #     command: npm start
    #     ports: 
    #         - "9001:9001"
    #     volumes: 
    #         - ./src:/usr/app
    #     container_name: node-container
    #     restart: always
    #     depends_on: 
    #         - db